[project]
name = "backend"
version = "0.1.0"
description = "Backend of the inventory management application."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.2",
]
